

TELEGRAM_API_KEY = ""
TELEGRAM_GROUP_CHAT_ID = ""
TELEGRAM_CHAT_ID_TG = ""
TELEGRAM_CHAT_ID_MA = ""

MQTT_BROKER_ADDR = "localhost"
MQTT_BROKER_PORT = 1883
MQTT_BROKER_TIMEOUT = 60
CMD_TOPIC = "/TOPIC"

